# Generated by Django 3.2.7 on 2021-09-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cutomer',
            new_name='is_customer',
        ),
    ]
