# Generated by Django 3.1.3 on 2021-09-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210910_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cutomer',
            new_name='is_customer',
        ),
    ]
